[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

# Gruvbox dark color scheme
[colors.primary]
background = "#1d2021"
foreground = "#ebdbb2"

[colors.cursor]
text = "#1d2021"
cursor = "#ebdbb2"

[colors.selection]
text = "#1d2021"
background = "#83a598"

[colors.normal]
black   = "#1d2021"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"

# [window]
#   opacity = 0.8

[font]
size = 15.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
