[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

# Gruvbox dark color scheme
[colors.primary]
background = "#1d2021"
foreground = "#ebdbb2"

[colors.cursor]
text = "#1d2021"
cursor = "#ebdbb2"

[colors.selection]
text = "#1d2021"
background = "#83a598"

[colors.normal]
black   = "#1d2021"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"

[window]
dynamic_padding = false
dynamic_title = true
opacity = 0.8

[window.class]
general = "Alacritty"
instance = "Alacritty"

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"

[font]
size = 16.0

[font.normal]
family = "AnonymicePro Nerd Font"
style = "Bold"

[font.bold]
family = "AnonymicePro Nerd Font"
style = "Bold"

[font.italic]
family = "AnonymicePro Nerd Font"
style = "Bold Italic"

[font.bold_italic]
family = "AnonymicePro Nerd Font"
style = "Bold Italic"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[scrolling]
history = 5000

[selection]
save_to_clipboard = true
