#!/usr/bin/env bash
set -euo pipefail

echo "Installing packages..."

sudo apt update
sudo apt install -y \
  neofetch lsd kitty tmux python3 python3-pip python3-libtmux zsh zoxide fzf nitrogen \
  picom clang build-essential ninja-build gettext libtool libtool-bin autoconf \
  automake cmake g++ pkg-config unzip curl doxygen git

echo "Installing Oh My Zsh..."

if [ ! -d "$HOME/.oh-my-zsh" ]; then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
fi

git clone https://github.com/zdharma-continuum/fast-syntax-highlighting \
  ~/.zsh/fast-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions

echo "Creating config symlinks..."

mkdir -p ~/.config

ln -sf "$(pwd)"/zsh/plugins ~/.oh-my-zsh/custom/plugins
ln -sf "$(pwd)"/tmux/.tmux.conf ~/.tmux.conf
ln -sf "$(pwd)"/zsh/.zshrc ~/.zshrc
ln -sf "$(pwd)"/alacritty ~/.config/alacritty
ln -sf "$(pwd)"/awesome ~/.config/awesome
ln -sf "$(pwd)"/i3 ~/.config/i3
ln -sf "$(pwd)"/kitty ~/.config/kitty
ln -sf "$(pwd)"/nvim ~/.config/nvim
ln -sf "$(pwd)"/picom ~/.config/picom

echo "Done."
