#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# I need to know which window I am in
bspc config border_width         3
bspc config focused_border_color "#458588"

# Gaps are stupid
bspc config window_gap           0

# EVERYTHING SHOULD BE PROPORTIONATE
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config single_monocle       true
bspc config gapless_monocle      true

# Fix that annoying cursor
xsetroot -cursor_name left_ptr &

~/.fehbg &
polybar example &
urxvtd &
